#!/usr/bin/env bash

[[ "${1,,}" != +(\-)@(h)?(elp) ]] || { cat <<'EOL'

USAGE:
         ask [<OPTION>] [<QUESTION>]

SYNOPSIS:
      Prompt the user with an ostensibly yes-or-no QUESTION (all input is optional).
      Returns 0(true) for (y|yes), or 1(false) for (n|no).
      If no QUESTION is provided it will simply prompt for a '(Y/n)' response.
      Response is case-insensitive.

OPTIONS:
   (*) OPTIONS must precede QUESTION if supplied.
   (*) Trailing args always comprise QUESTION (escapes are interpretted).

   -h,--help   show this helpful usage information

   -y,--yes    fail if answer is not (y|yes)

   -n,--no     fail if answer is not (n|no)

   -l,         repeatedly ask [<QUESTION>] until a desired response is given.
    --loop     the desired response can be set using the (`-y`|`--yes`) and (`-n`|`--no`) flags,
               (default is (y|yes) )

   -s,         ask [<QUESTION>] again if a response
    --strict    other than (y|yes) or (n|no) is given

   -p,         write the response to STDOUT
    --prompt   (deactivates all other options)
               (causes `ask` to function as a simple read prompt)
               (optional: ` --prompt=MESSAGE `)

EOL
	exit 0
}

shopt -s extglob

Ask='Ask'
Desire='@(y)?(es)'
PromptLine='(response): '
for((p=0,a=1;a<=$#;a++)){
  case "${!a,,}" in
  '-y'|'--yes') ((p=a)) ;;
  '-n'|'--no') ((p=a)); Desire='@(n)?(o)' ;;
  '-s'|'--strict') ((p=a)); Ask='Strict' ;;
  '-l'|'--loop') ((p=a)); Action='Pester' ;;
  +(\-)@(p)?(rompt)?(\=)*) ((p=a)); Action='Tell'
    [[ "${!a}" != *\=* ]] || PromptLine="${!a#*\=}" ;;
  *) continue
  esac
}

Ask() { local Ans ; printf "${*:2}\n" ; read -p '(Y/n): ' Ans ; [[ "${Ans,,}" == ${1} ]] ; }

Strict() {
	printf "${*:2}\n"
	read -p '(Y/n): ' Ans
	[[ "${Ans,,}" == @(n?(o)|y?(es)) ]] || Strict ${1} "${*:2}"
	[[ "${Ans,,}" == $1 ]]
}

Pester() { $Ask "$1" "${@:2}" || Pester "$1" "${*:2}"; }

Tell() { local Ans; printf "${*:2}\n" >/dev/stderr || true; read -p "$PromptLine" Ans ; echo "$Ans"; }

${Action:-$Ask} "$Desire" "${*:$((++p))}"
